---
- name: Facts
  hosts: linuxservers

  tasks:
    - name: Debug Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

        state: reloaded

    - name: Debug Facts Hostname - Unsafe Text
      ansible.builtin.debug:
        msg: "{{ ansible_facts['nodename'] }}"
